version: '3.3'

services:
  web2:
    build: ..
    ports:
      - '16203:80'
    environment:
      DEMO_NAME: Web2
      SPRING_DATASOURCE_URL: jdbc:postgresql://18.184.218.192:5432/chinook
      SPRING_DATASOURCE_USERNAME: vagrant
      SPRING_DATASOURCE_PASSWORD: vagrant
