version: '3.3'

services:
  db:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./chinook_data.sql:/docker-entrypoint-initdb.d/chinook_data.sql
    ports:
      - 16200:5432
    restart: always
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: chinook
volumes:
  db_data: